SELECT * FROM CAT_ROLES;
SELECT * FROM CAT_USERS;

--INSERT INTO CAT_USERS (USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, ROLID, ADDRESS, ZIPCODE, PHONE, CELPHONE, ACTIVE) 
--		VALUES ('ADMIN', 'ADMIN', 'ADMIN', 'ADMIN', '1', 'MTY', '66450', '0', '0', 'TRUE');


SELECT * FROM CAT_USERS WHERE USERNAME = 'ADMIN' AND PASSWORD = 'ADMIN';